name: Build and Push Docker Images to Docker Hub with Docker Compose

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout app repo
        uses: actions/checkout@v3
        with:
          repository: shreya13p/opentelemetry-demo
          token: ${{ secrets.PERSONAL_TOKEN }}  # GitHub Personal Access Token stored securely

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Build Docker images using Docker Compose
      - name: Build Docker Images
        run: |
          docker-compose -f docker-compose.yml build

      # Tag and Push Docker Images to Docker Hub
      - name: Tag and Push Docker Images to Docker Hub
        run: |
          # Get the list of services in docker-compose file and push images to Docker Hub
          for SERVICE in $(docker-compose -f docker-compose.yml config --services); do
            IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/${SERVICE}:latest"
            # Tag the image for Docker Hub
            docker tag "$SERVICE" "$IMAGE_NAME"
            # Push the image to Docker Hub
            docker push "$IMAGE_NAME"
          done
