name: Deploy to EKS

on:
  workflow_run:
    workflows: ["Build and Push Image"]
    types: [completed]
on:
  workflow_dispatch:  # <-- enables manual trigger
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout helm chart repo
        uses: actions/checkout@v3
        with:
          repository: shreya13p/opentelemetry-helm-charts
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{variables.cluster_name}}

      - name: Helm Deploy
        run: |
          helm upgrade --install otel-demo ./charts/opentelemetry-demo \
            --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/otel-demo \
            --set image.tag=latest

      - name: Run Smoke Test
        run: |
          chmod +x test/smoke_test.sh
          ./test/smoke_test.sh

